---
branding: nixos
sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - users
    - partition
    - summary
  - exec:
    - partition
    - mount
    - nixos-flake
    - umount
  - show:
    - finished
prompt-install: false
dont-chroot: false
disable-cancel: false
disable-cancel-during-exec: true
