# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "mpt3sas" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-e60d11b8-a04f-4be3-ac52-fcb96110a677";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-e60d11b8-a04f-4be3-ac52-fcb96110a677".device = "/dev/disk/by-uuid/e60d11b8-a04f-4be3-ac52-fcb96110a677";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/731C-1BE6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-6665f9fc-a50c-4ec2-b301-ab49ffe83b86"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
