# Do not modify this file! It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations. Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-fdfea18c-9c2e-4e63-b2ab-816137e79182";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-fdfea18c-9c2e-4e63-b2ab-816137e79182".device = "/dev/disk/by-uuid/fdfea18c-9c2e-4e63-b2ab-816137e79182";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F899-A579";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [{device = "/dev/mapper/luks-b88560c3-c549-479f-8357-e52c43bf0684";}];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
