# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-2f6e2253-9bc3-4447-bd1a-5767eb75bf54";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-2f6e2253-9bc3-4447-bd1a-5767eb75bf54".device = "/dev/disk/by-uuid/2f6e2253-9bc3-4447-bd1a-5767eb75bf54";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5680-9222";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-42997d57-8a2a-443a-851b-79ae5ec6dd42"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
