# Generated by purr — do not edit
# Source: Purr DSL -> Nix
{
  imports = [];
  config = {
    # bundle dev-bundle
    # description: Dev bundle
    # programs: git, helix
    # packageToggles: dev
    # preset gaming-base
    # description: Base gaming
    gaming.enable = true;
    # host testhost
    networking.hostName = "testhost";
    # use role desktop
    flakesonnix.fonts.inter = true;
    niri.users = [ "lucy" ];
    # preset gaming-base
    flakesonnix.gaming.enable = true;
  };
}
