# Generated by purr — do not edit
# Source: Purr DSL -> Nix
{
  imports = [];
  config = {
    # host base
    networking.hostName = "base";
    # use role desktop
    flakesonnix.fonts.inter = true;
    niri.users = [ "lucy" ];
    # packages tags: curl, git
    # host web
    networking.hostName = "web";
    # use role desktop
    flakesonnix.fonts.inter = true;
    niri.users = [ "lucy" ];
    # packages tags: curl, git, nginx
    # use role gaming
    flakesonnix.gaming.enable = true;
  };
}
