# Generated by purr — do not edit
# Source: Purr DSL -> Nix
{
  imports = [];
  config = {
    # role desktop
    # description: Desktop
    # host x270
    networking.hostName = "x270";
    # package "git"
    environment.systemPackages = with pkgs; [ git ];
    # use role desktop
    flakesonnix.fonts.inter = true;
    niri.users = [ "lucy" ];
  };
}
