const std = @import("std");
const ast = @import("ast.zig");

pub fn generate(program: *const ast.Program, allocator: std.mem.Allocator) ![]const u8 {
    var buf: std.ArrayList(u8) = .empty;
    try buf.appendSlice(allocator, "# Generated by purr — do not edit\n");
    try buf.appendSlice(allocator, "# Source: Purr DSL -> Nix\n");
    try buf.appendSlice(allocator, "{\n");
    try buf.appendSlice(allocator, "  imports = [];\n");
    try buf.appendSlice(allocator, "  config = {\n");

    for (program.decls) |decl| {
        switch (decl) {
            .host => |h| {
                try buf.appendSlice(allocator, "    # host ");
                try buf.appendSlice(allocator, h.name.name);
                try buf.appendSlice(allocator, "\n");
                try buf.appendSlice(allocator, "    networking.hostName = \"");
                try buf.appendSlice(allocator, h.name.name);
                try buf.appendSlice(allocator, "\";\n");
                // collect packages to emit aggregated systemPackages (avoid duplicate attr)
                var pkgs: std.ArrayList([]const u8) = .empty;
                defer pkgs.deinit(allocator);
                for (h.stmts) |stmt| if (stmt == .package) try pkgs.append(allocator, stmt.package);
                if (pkgs.items.len > 0) {
                    for (pkgs.items) |p| {
                        try buf.appendSlice(allocator, "    # package \"");
                        try buf.appendSlice(allocator, p);
                        try buf.appendSlice(allocator, "\"\n");
                    }
                    try buf.appendSlice(allocator, "    environment.systemPackages = with pkgs; [ ");
                    for (pkgs.items, 0..) |p, idx| {
                        if (idx > 0) try buf.appendSlice(allocator, " ");
                        try buf.appendSlice(allocator, p);
                    }
                    try buf.appendSlice(allocator, " ];\n");
                }
                for (h.stmts) |stmt| {
                    switch (stmt) {
                        .use_role => |ident| {
                            try buf.appendSlice(allocator, "    # use role ");
                            try buf.appendSlice(allocator, ident.name);
                            try buf.appendSlice(allocator, "\n");
                            // map roles to flakesonnix presets/tags via framework
                            // for now emit comment and placeholder
                            if (std.mem.eql(u8, ident.name, "desktop")) {
                                try buf.appendSlice(allocator, "    flakesonnix.fonts.inter = true;\n");
                                try buf.appendSlice(allocator, "    niri.users = [ \"lucy\" ];\n");
                            } else if (std.mem.eql(u8, ident.name, "gaming")) {
                                try buf.appendSlice(allocator, "    flakesonnix.gaming.enable = true;\n");
                            }
                        },
                        .preset => |ident| {
                            try buf.appendSlice(allocator, "    # preset ");
                            try buf.appendSlice(allocator, ident.name);
                            try buf.appendSlice(allocator, "\n");
                            if (std.mem.eql(u8, ident.name, "gaming-base")) {
                                try buf.appendSlice(allocator, "    flakesonnix.gaming.enable = true;\n");
                            } else if (std.mem.eql(u8, ident.name, "gaming-performance")) {
                                try buf.appendSlice(allocator, "    flakesonnix.gaming.performance.enable = true;\n");
                            } else if (std.mem.eql(u8, ident.name, "gaming-steam")) {
                                try buf.appendSlice(allocator, "    flakesonnix.gaming.steam.enable = true;\n");
                            }
                        },
                        .package => {}, // already emitted aggregated above
                        .packages_assign => |tags| {
                            try buf.appendSlice(allocator, "    # packages tags: ");
                            for (tags, 0..) |t, i| {
                                if (i > 0) try buf.appendSlice(allocator, ", ");
                                try buf.appendSlice(allocator, t);
                            }
                            try buf.appendSlice(allocator, "\n");
                        },
                        .setting => |s| {
                            if (std.mem.eql(u8, s.path, "nix_raw")) {
                                // raw nix escape inside host
                                try buf.appendSlice(allocator, "    # nix raw inside host\n");
                                switch (s.value) {
                                    .string => |raw| try buf.appendSlice(allocator, raw),
                                    else => try writeValueBuf(&buf, allocator, s.value),
                                }
                                try buf.appendSlice(allocator, "\n");
                            } else {
                                try buf.appendSlice(allocator, "    # setting ");
                                try buf.appendSlice(allocator, s.path);
                                try buf.appendSlice(allocator, "\n");
                                try buf.appendSlice(allocator, "    ");
                                try buf.appendSlice(allocator, s.path);
                                try buf.appendSlice(allocator, " = ");
                                try writeValueBuf(&buf, allocator, s.value);
                                try buf.appendSlice(allocator, ";\n");
                            }
                        },
                    }
                }
            },
            .role => |r| {
                try buf.appendSlice(allocator, "    # role ");
                try buf.appendSlice(allocator, r.name.name);
                try buf.appendSlice(allocator, "\n");
                if (r.description) |d| {
                    try buf.appendSlice(allocator, "    # description: ");
                    try buf.appendSlice(allocator, d);
                    try buf.appendSlice(allocator, "\n");
                }
                // roles themselves don't emit Nix directly; hosts consume them
            },
            .nix => |n| {
                try buf.appendSlice(allocator, "    # nix escape hatch\n");
                try buf.appendSlice(allocator, n.content);
                try buf.appendSlice(allocator, "\n");
            },
            else => {
                try buf.appendSlice(allocator, "    # (other decl)\n");
            },
        }
    }

    try buf.appendSlice(allocator, "  };\n");
    try buf.appendSlice(allocator, "}\n");
    return try buf.toOwnedSlice(allocator);
}

fn writeValueBuf(buf: *std.ArrayList(u8), allocator: std.mem.Allocator, v: ast.Value) !void {
    switch (v) {
        .string => |s| {
            try buf.appendSlice(allocator, "\"");
            try buf.appendSlice(allocator, s);
            try buf.appendSlice(allocator, "\"");
        },
        .integer => |i| {
            const s = try std.fmt.allocPrint(allocator, "{d}", .{i});
            defer allocator.free(s);
            try buf.appendSlice(allocator, s);
        },
        .boolean => |b| {
            if (b) try buf.appendSlice(allocator, "true") else try buf.appendSlice(allocator, "false");
        },
        .ident => |id| {
            try buf.appendSlice(allocator, id.name);
        },
        .list => |lst| {
            try buf.appendSlice(allocator, "[ ");
            for (lst, 0..) |item, idx| {
                if (idx > 0) try buf.appendSlice(allocator, " ");
                try writeValueBuf(buf, allocator, item);
            }
            try buf.appendSlice(allocator, " ]");
        },
    }
}

test "nix generate deterministic" {
    const alloc = std.testing.allocator;
    var arena = std.heap.ArenaAllocator.init(alloc);
    defer arena.deinit();
    const source = "host x270 { use desktop; package \"git\"; }";
    const diagnostics = @import("diagnostics.zig");
    var diag = diagnostics.Diagnostics.init(arena.allocator(), "test.meow", source);
    const lexer = @import("lexer.zig");
    var lex = lexer.Lexer.init(source, "test.meow", &diag);
    const toks = try lex.lexAll(arena.allocator());
    var parser = @import("parser.zig").Parser.init(toks, &diag, &arena);
    var prog = try parser.parseProgram();
    const out1 = try generate(&prog, arena.allocator());
    const out2 = try generate(&prog, arena.allocator());
    try std.testing.expectEqualStrings(out1, out2);
}
