/*
* Asterisk Local SIP PBX Module
*
* A higher-level, opinionated interface for running a local internal phone
* network using Asterisk with PJSIP (the modern SIP stack).
*
* IMPORTANT: Asterisk does NOT auto-restart on `nixos-rebuild switch` by default.
* It performs a live reload of its configuration instead. After running
* `nixos-rebuild switch`, you MUST run one of:
*
*   sudo asterisk -rx 'core reload'   # Live reload (preserves calls)
*   sudo systemctl restart asterisk    # Full restart (drops active calls)
*
* This module generates configuration files for:
*   - pjsip.conf   (SIP transport, endpoints, auth, AORs)
*   - extensions.conf (dial plan)
*
* SECURITY WARNING: Passwords are stored in plaintext in Asterisk config files.
* For production use, integrate with a secrets manager (e.g. agenix, sops-nix)
* to inject passwords at runtime rather than storing them in the Nix store.
*/
{
  config,
  lib,
  ...
}: let
  cfg = config.services.asteriskLocal;
  hasPhonePassword = phone: phone.password != null || phone.passwordFile != null || phone.passwordSopsKey != null;

  phonesWithRuntimeSecrets = lib.filterAttrs (_: phone: phone.passwordFile != null || phone.passwordSopsKey != null) cfg.phones;

  phonePasswordPath = phone:
    if phone.passwordFile != null
    then phone.passwordFile
    else config.sops.secrets.${phone.passwordSopsKey}.path;

  sopsSecretDefinitions = builtins.listToAttrs (
    lib.concatMap (
      name: let
        phone = cfg.phones.${name};
      in
        lib.optional (phone.passwordSopsKey != null) {
          name = phone.passwordSopsKey;
          value = {};
        }
    ) (builtins.attrNames cfg.phones)
  );

  writeRuntimeAuthStanza = name: phone: let
    passwordPath = lib.escapeShellArg (toString (phonePasswordPath phone));
  in ''
    password="$(tr -d '\n' < ${passwordPath})"
    cat >> /run/asterisk-local/pjsip.auth.conf <<EOF
    [${name}](auth_userpass)
    password = $password
    username = ${name}

    EOF
  '';

  runtimeAuthPreStart = ''
    install -d -m 0750 -o asterisk -g asterisk /run/asterisk-local
    cat > /run/asterisk-local/pjsip.auth.conf <<'EOF'
    ; ----------------------------------------------------------------
    ; PHONE AUTHENTICATION
    ; Generated at service start so passwords stay out of the Nix store.
    ; ----------------------------------------------------------------
    EOF
    chown asterisk:asterisk /run/asterisk-local/pjsip.auth.conf
    chmod 0640 /run/asterisk-local/pjsip.auth.conf
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList writeRuntimeAuthStanza phonesWithRuntimeSecrets)}
  '';

  /*
  * Generate pjsip.conf content
  *
  * PJSIP uses a three-stanza pattern for each phone endpoint:
  *   1. endpoint  - Defines the SIP endpoint (phone) with references to auth and aor
  *   2. auth      - Contains the authentication credentials (username + password)
  *   3. aor       - Address of Record - controls registration settings like max_contacts
  *
  * The template syntax (!) allows stanzas to inherit from a base template.
  * For example, [endpoint_internal](!) creates a template that other stanzas
  * can inherit from by specifying (endpoint_internal) after their own bracket name.
  */
  pjsipConf = ''
    ; ===============================================================
    ; pjsip.conf - Generated by services.asteriskLocal
    ; ===============================================================
    ; Built at: ${builtins.currentTime}
    ; ===============================================================

    ; ----------------------------------------------------------------
    ; TRANSPORT SECTION
    ; Defines how Asterisk listens for SIP connections
    ; ----------------------------------------------------------------
    [transport-${cfg.transport.protocol}]
    type = transport
    protocol = ${cfg.transport.protocol}
    bind = ${cfg.transport.bind}:5060
    ; Allow foreign SIP elements to register (e.g. external extensions)
    allow_reload = true
    ; Keepalive intervals for NAT traversal
    media_use_received_transport = true

    ; ----------------------------------------------------------------
    ; ENDPOINT TEMPLATE
    ; The (!) syntax creates a template that can be inherited.
    ; All actual endpoints inherit these base settings.
    ; ----------------------------------------------------------------
    [endpoint_internal](!)
    type = endpoint
    context = from-internal
    disallow = all
    allow = ulaw,alaw,g722
    direct_media = no
    connected_line_method = invite
    rtp_symmetric = yes
    force_rport = yes
    rewrite_contact = yes
    ; Voicemail extension for unanswered calls
    voicemail = default

    ; ----------------------------------------------------------------
    ; AUTH TEMPLATE
    ; Template for SIP authentication credentials
    ; ----------------------------------------------------------------
    [auth_userpass](!)
    type = auth
    auth_type = userpass

    #include /run/asterisk-local/pjsip.auth.conf

    ; ----------------------------------------------------------------
    ; AOR TEMPLATE
    ; Address of Record - controls registration behavior
    ; ----------------------------------------------------------------
    [aor_dynamic](!)
    type = aor
    contact = sip:${cfg.transport.bind}:5060
    ; Remove bindings when registration expires
    remove_existing = yes

    ; ----------------------------------------------------------------
    ; PHONE ENDPOINTS
    ; Generated from services.asteriskLocal.phones configuration
    ; ----------------------------------------------------------------
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList generatePhoneStanzas cfg.phones)}

    ; ----------------------------------------------------------------
    ; TRUNK TEMPLATE (for future external SIP trunk integration)
    ; ----------------------------------------------------------------
    [trunk](!)
    type = endpoint
    context = from-external
    disallow = all
    allow = ulaw,alaw,g722
    direct_media = no
  '';

  /*
  * Generate all stanzas for a single phone
  * Each phone gets: endpoint, auth, and aor stanzas
  */
  generatePhoneStanzas = name: phone: let
    # Build the endpoint stanza - inherits from endpoint_internal template
    endpoint = ''
      [${name}](endpoint_internal)
      auth = ${name}
      aors = ${name}
    '';

    # Build the auth stanza - inherits from auth_userpass template
    # Contains the SIP password (plaintext - see security warning above)
    auth =
      if phone.password != null
      then ''
        [${name}](auth_userpass)
        password = ${phone.password}
        username = ${name}
      ''
      else "";

    # Build the AOR stanza - inherits from aor_dynamic template
    # Controls registration behavior (max_contacts limits simultaneous devices)
    aor = ''
      [${name}](aor_dynamic)
      max_contacts = ${toString phone.maxContacts}
    '';
  in
    lib.concatStringsSep "\n" [endpoint auth aor];

  /*
  * Generate extensions.conf content
  *
  * The dial plan maps extension numbers to actions.
  * Each extension line follows the format:
  *   exten => NUMBER,PRIORITY,ACTION
  *
  * The 'n' priority means "next" - continues to the next priority number.
  * 'same => n,...' is shorthand for repeating the same extension number.
  */
  extensionsConf = ''
    ; ===============================================================
    ; extensions.conf - Generated by services.asteriskLocal
    ; ===============================================================
    ; Built at: ${builtins.currentTime}
    ; ===============================================================

    [general]
    ; Static configuration for dialplan behavior
    static = yes
    writeprotect = no
    ; Clean up dialplan reloads
    clearglobalvars = no

    [globals]
    ; Global variables that can be used in extensions
    TIMEOUT = 20

    ; ----------------------------------------------------------------
    ; FROM-INTERNAL CONTEXT
    ; Handles calls from registered internal extensions
    ; ----------------------------------------------------------------
    [from-internal]
    ; Include feature codes for transfers, parking, etc.
    include => featuremap

    ; ----------------------------------------------------------------
    ; DEBUGGING EXTENSION
    ; Test extension 100 plays a test message - useful for verifying
    ; that your SIP client can connect and Asterisk is processing calls.
    ; Call extension 100 from any phone to verify basic functionality.
    ; ----------------------------------------------------------------
    exten => 100,1,Answer()
        same => n,Wait(1)
        same => n,Playback(hello-world)
        same => n,Hangup()

    ; ----------------------------------------------------------------
    ; PHONE EXTENSIONS
    ; Generated from services.asteriskLocal.phones configuration
    ; Dial(name,timeout) connects to the PJSIP endpoint named name
    ; ----------------------------------------------------------------
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList generateExtension cfg.phones)}

    ; ----------------------------------------------------------------
    ; FEATURE MAP
    ; Key-based call transfer and parking features
    ; ----------------------------------------------------------------
    [featuremap]
    ; Blind transfer (press *2 followed by extension)
    blindxfer => *2
    ; Attended transfer (press *3 followed by extension)
    atxfer => *3
    ; One-touch recording (press *1 to toggle)
    automon => *1
    ; Call park (press #72 to park, #74 to retrieve)
    parkcall => #72
    ; Disconnect call
    disconnect => *0

    ; ----------------------------------------------------------------
    ; RING GROUP EXAMPLE (uncomment to use)
    ; Uncomment the following to create a ring group that calls all phones
    ; simultaneously when dialing extension 9000.
    ; ----------------------------------------------------------------
    ; exten => 9000,1,NoOp(Ring all extensions)
    ;     same => n,Dial(PJSIP/phone1&PJSIP/phone2,20)
    ;     same => n,Hangup()

    ; ----------------------------------------------------------------
    ; USER-DEFINED EXTENSIONS
    ; From services.asteriskLocal.extraExtensions
    ; ----------------------------------------------------------------
    ${cfg.extraExtensions}
  '';

  /*
  * Generate a single extension dial entry
  * Format: exten => NUMBER,PRIORITY,Dial(PJSIP/name,timeout)
  */
  generateExtension = name: phone: "exten => ${phone.extension},1,Dial(PJSIP/${name},${toString phone.dialTimeout})";

  /*
  * Validate configuration and emit warnings/errors
  */
  configAssertions = [
    # Check for duplicate extension numbers
    {
      assertion = let
        extensions-list = lib.mapAttrsToList (_name: phone: phone.extension) cfg.phones;
        unique-extensions = lib.unique extensions-list;
      in
        lib.length extensions-list == lib.length unique-extensions;
      message = "asteriskLocal: duplicate extension numbers detected. Each phone must have a unique extension.";
    }
  ];

  /*
  * Emit security warnings for weak credentials
  * This uses lib.warn to alert operators about potential security issues
  * without blocking the configuration from building.
  */
  credentialWarnings = let
    phones-list =
      lib.mapAttrsToList (name: phone: {
        inherit name;
        inherit (phone) password;
      })
      cfg.phones;
    weak-creds = lib.filter (p: p.name == p.password) phones-list;
  in
    lib.concatStringsSep "\n" (lib.map (p: "asteriskLocal: phone '${p.name}' has password equal to account name - this is a weak credential") weak-creds);
in {
  options.services.asteriskLocal = {
    enable = lib.mkEnableOption (lib.mdDoc ''
      local Asterisk SIP PBX server using PJSIP.

      This module creates a simple internal phone network where SIP clients
      (softphones, IP phones) can register with Asterisk using extension
      numbers and make calls to each other.

      After enabling, you must reload Asterisk configuration:
        sudo asterisk -rx 'core reload'
    '');

    transport = {
      protocol = lib.mkOption {
        type = lib.types.enum ["udp" "tcp" "tls"];
        default = "udp";
        description = lib.mdDoc ''
          SIP transport protocol.

          - `udp`: Unencrypted UDP (default, works everywhere)
          - `tcp`: Unencrypted TCP (useful for NAT traversal)
          - `tls`: Encrypted TCP (requires certificates for production)
        '';
      };

      bind = lib.mkOption {
        type = lib.types.str;
        default = "0.0.0.0";
        description = lib.mdDoc ''
          Address to bind the SIP transport to.

          - `0.0.0.0`: Bind to all interfaces (default)
          - `127.0.0.1`: Localhost only
          - Specific IP: Bind to specific interface
        '';
      };
    };

    phones = lib.mkOption {
      type = lib.types.attrsOf (lib.types.submodule {
        options = {
          extension = lib.mkOption {
            type = lib.types.str;
            description = lib.mdDoc ''
              Dial plan extension number, e.g. "1001".
              Must be unique across all phones.
            '';
          };

          password = lib.mkOption {
            type = lib.types.nullOr lib.types.str;
            default = null;
            description = lib.mdDoc ''
              SIP account password (plaintext).

              SECURITY WARNING: This password will be stored in plaintext
              in /etc/asterisk/pjsip.conf in the Nix store. For production
              use, integrate with a secrets manager (agenix, sops-nix) to
              inject passwords at runtime.
            '';
          };

          passwordFile = lib.mkOption {
            type = lib.types.nullOr lib.types.path;
            default = null;
            description = lib.mdDoc ''
              Path to a file containing the SIP account password.

              The file is read when Asterisk starts so the password stays out
              of the Nix store.
            '';
          };

          passwordSopsKey = lib.mkOption {
            type = lib.types.nullOr lib.types.str;
            default = null;
            description = lib.mdDoc ''
              Name of a sops-nix secret whose content becomes this phone's SIP
              password at service start.
            '';
          };

          dialTimeout = lib.mkOption {
            type = lib.types.int;
            default = 20;
            description = lib.mdDoc ''
              Seconds to ring before giving up and returning busy signal.
            '';
          };

          maxContacts = lib.mkOption {
            type = lib.types.int;
            default = 1;
            description = lib.mdDoc ''
              Maximum number of simultaneous registrations allowed for this
              AOR (Address of Record). Set higher if you have multiple
              devices (e.g. desk phone + softphone) sharing one extension.
            '';
          };
        };
      });
      default = {};
      description = lib.mdDoc ''
        Attribute set of phones keyed by account name.

        Each phone generates:
        - An endpoint stanza in pjsip.conf
        - An auth stanza in pjsip.conf
        - An aor stanza in pjsip.conf
        - A corresponding Dial() line in extensions.conf

        Example:
          phones = {
            saal1 = { extension = "1001"; passwordSopsKey = "asterisk-saal1-password"; };
            backoffice = { extension = "1600"; passwordSopsKey = "asterisk-backoffice-password"; };
          };
      '';
    };

    extraExtensions = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = lib.mdDoc ''
        Extra lines appended verbatim to the [from-internal] context
        in extensions.conf. Useful for adding:
        - Test extensions
        - Voicemail configuration
        - Ring groups
        - IVR menus
      '';
    };

    openFirewall = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = lib.mdDoc ''
        Open UDP ports in the firewall for SIP and RTP media.

        - UDP 5060: SIP signaling
        - UDP 10000-20000: RTP media (audio streams)

        Only enable this on trusted networks. For production, consider
        using VPN or restricting to specific source IPs.
      '';
    };

    # Enable live reload instead of restart (preserves active calls)
    liveReload = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = lib.mdDoc ''
        If true, Asterisk will reload configuration on nixos-rebuild switch
        instead of restarting. This preserves active calls but new extensions
        or configuration changes may not take full effect until a full restart.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # Enable the Asterisk service
    services.asterisk = {
      enable = true;

      # Generated configuration files
      confFiles = {
        # pjsip.conf - SIP endpoint configuration
        "pjsip.conf" = pjsipConf;

        # extensions.conf - Dial plan
        "extensions.conf" = extensionsConf;

        # Disable unneeded modules for a simple internal PBX
        "asterisk.conf" = "[modules]\nautoload = no\n; Load only what we need for basic SIP functionality\npreload => res_pjsip.so\npreload => res_pjsip_session.so\npreload => app_dial.so\npreload => app_playback.so\npreload => func_callerid.so\n";
      };
    };

    # Firewall configuration
    networking.firewall = lib.mkIf cfg.openFirewall {
      allowedUDPPorts = [5060];
      allowedUDPPortRanges = [
        {
          from = 10000;
          to = 20000;
        } # RTP media port range
      ];
    };

    # Configuration assertions - fail early if configuration is invalid
    assertions =
      configAssertions
      ++ [
        {
          assertion = lib.all hasPhonePassword (lib.attrValues cfg.phones);
          message = "asteriskLocal: each phone must set one of password, passwordFile, or passwordSopsKey.";
        }
        {
          assertion = lib.all (
            phone:
              lib.length (
                lib.filter (value: value != null) [
                  phone.password
                  phone.passwordFile
                  phone.passwordSopsKey
                ]
              )
              == 1
          ) (lib.attrValues cfg.phones);
          message = "asteriskLocal: each phone must set exactly one of password, passwordFile, or passwordSopsKey.";
        }
        {
          assertion = phonesWithRuntimeSecrets == {} || config.lucy.secrets.enable;
          message = "asteriskLocal: passwordFile/passwordSopsKey requires lucy.secrets.enable so runtime secret paths are managed declaratively.";
        }
        # Warn about weak credentials
        {
          assertion = lib.length credentialWarnings == 0;
          message = "asteriskLocal: ${credentialWarnings}";
        }
      ];

    sops.secrets = sopsSecretDefinitions;

    systemd.services.asterisk.preStart = lib.mkAfter runtimeAuthPreStart;
  };
}
