/*
* VoIP/SIP client abstraction (Phase 1: structure only, no live trunk yet)
*
* Goal topology (later):
*   Internet SIP provider (e.g. Easybell)
*     -> NixOS VoIP service (Asterisk PJSIP, see services.asteriskLocal)
*     -> local clients / internal SIP endpoints
*
* This module intentionally does NOT implement the provider trunk yet.
* Phase 1 provides the stable, typed API + validation + sops-ready secret
* wiring + a provider-free local test extension. The trunk renderer
* (PJSIP registration/endpoint/auth/aor, cf. Easybell's official
* Asterisk-22 guide) is Phase 2 and will consume the descriptors written
* to /etc/voip/clients/*.conf by this module.
*
* Design notes:
* - Soft dependency on modules/nixos/asterisk.nix (localTest assertion
*   + extraExtensions hook, guarded via `options`). True on x270 via
*   flake.nix; without it localTest fails with a clear message.
* - Reuses the existing Asterisk 22 stack (nixpkgs nixos-unstable,
*   same major version as Easybell's official Asterisk guide). No new
*   dependencies: baresip is client-only (no dialplan/routing for
*   Nebenstellen), FreeSWITCH/Kamailio would be new heavy stacks.
* - Secrets NEVER enter the Nix store: only *paths* (passwordFile) are
*   stored. Point them at sops-nix secret paths, e.g.
*     passwordFile = config.sops.secrets."voip/easybell-main".path;
*   See docs/secrets.md ("VoIP secrets").
* - No firewall changes here. See NETWORKING TODO below.
*
* NETWORKING TODO (Phase 2, do not implement yet):
* - Easybell needs (unencrypted): SIP 5060 or 5064 UDP/TCP, RTP
*   20000-50000 UDP/TCP; encrypted: SIP 5061 TLS, same RTP range.
*   Sources: easybell.de/help "Configuring the firewall for Easybell
*   VoIP and SIP trunking", "VoIP configuration for advanced users".
* - MISMATCH: services.asteriskLocal.openFirewall currently opens RTP
*   10000-20000 only. Before going live, align the RTP range with the
*   Easybell product in use (phone numbers: 20000-50000).
* - Easybell guidance: STUN off, outbound proxy = registrar, no fixed
*   port forwarding, no SIP ALG, no multi-WAN/load-balancing for voice.
*   asteriskLocal already sets rtp_symmetric/force_rport/rewrite_contact.
* - Fail2Ban: Easybell bans source IPs after repeated failed REGISTERs.
*   Keep retry_interval conservative (default 60s) and never enable a
*   trunk with placeholder credentials.
*/
{
  config,
  lib,
  options,
  ...
}: let
  cfg = config.services.voip;

  # Soft dependency: asterisk.nix may be absent (e.g. hosts without a
  # voice stack). NOTE: this nixpkgs checks option paths structurally —
  # lib.mkIf false does NOT shield references to missing options — so
  # every services.asteriskLocal definition lives behind `hasAsterisk`
  # via lib.optionals (list element absent entirely when false).
  hasAsterisk = options.services ? asteriskLocal;

  enabledClients = lib.filterAttrs (_name: c: c.enable) cfg.clients;

  # Non-secret per-client descriptor (Phase-2 trunk renderer contract).
  # Contains only public data + the *path* to the credential file.
  clientDescriptor = name: client: let
    provider = cfg.providers.${client.provider};
  in ''
    # Generated by services.voip — Phase-1 descriptor (no secrets).
    # Phase 2 renders the Asterisk PJSIP trunk from these values plus
    # the password read at runtime from password_file.
    client=${name}
    provider=${client.provider}
    registrar=${provider.registrar}
    sip_port=${toString provider.port}
    transport=${provider.transport}
    username=${client.username}
    did=${client.did}
    display_name=${client.displayName}
    password_file=${client.passwordFile}
    expires=${toString provider.expires}
    retry_interval=${toString provider.retryInterval}
  '';

  # Local test extension (provider-free): SIP client -> Asterisk ->
  # playback. Uses only app_playback (already loaded by asteriskLocal's
  # modules.conf). NOTE: app_echo is NOT loaded there, so no Echo() yet.
  localTestLines = ''
    exten => ${cfg.localTest.extension},1,NoOp(VoIP local test ${cfg.localTest.extension})
        same => n,Answer()
        same => n,Wait(1)
        same => n,Playback(hello-world)
        same => n,Hangup()
  '';
in {
  options.services.voip = {
    enable = lib.mkEnableOption "generic VoIP/SIP client abstraction (Phase 1: descriptors + validation, no live provider trunk)";

    providers = lib.mkOption {
      type = lib.types.attrsOf (lib.types.submodule {
        options = {
          registrar = lib.mkOption {
            type = lib.types.nullOr lib.types.str;
            default = null;
            description = "SIP registrar hostname. Null = TODO, provider not usable yet.";
          };
          port = lib.mkOption {
            type = lib.types.port;
            default = 5060;
            description = "SIP port (Easybell: 5060, alt 5064; TLS 5061).";
          };
          transport = lib.mkOption {
            type = lib.types.enum ["udp" "tcp" "tls"];
            default = "udp";
            description = "SIP transport.";
          };
          outboundProxy = lib.mkOption {
            type = lib.types.nullOr lib.types.str;
            default = null;
            description = "Outbound proxy. Null = same as registrar (Easybell default).";
          };
          expires = lib.mkOption {
            type = lib.types.int;
            default = 1800;
            description = "Registration expiry in seconds (Easybell reference).";
          };
          retryInterval = lib.mkOption {
            type = lib.types.int;
            default = 60;
            description = "REGISTER retry interval. Keep conservative: Easybell Fail2Ban-bans sources with repeated failures.";
          };
          note = lib.mkOption {
            type = lib.types.str;
            default = "";
            description = "Free-form product notes (e.g. which Easybell product this registrar belongs to).";
          };
        };
      });
      default = {};
      description = "SIP provider presets keyed by name (e.g. easybell, eventphone). Clients reference these by name.";
    };

    clients = lib.mkOption {
      type = lib.types.attrsOf (lib.types.submodule {
        options = {
          provider = lib.mkOption {
            type = lib.types.str;
            default = "easybell";
            description = "Key into services.voip.providers.";
          };
          username = lib.mkOption {
            type = lib.types.nullOr lib.types.str;
            default = null;
            description = "SIP auth username (Easybell: e.g. K12345678 from the customer portal). Null until assigned via host config.";
          };
          passwordFile = lib.mkOption {
            type = lib.types.str;
            default = "";
            description = ''
              Absolute runtime path to a file containing the SIP password.
              Only the path enters the Nix store, never the secret.
              sops-nix wiring (later):
                sops.secrets."voip/<client>" = {};
                services.voip.clients.<client>.passwordFile =
                  config.sops.secrets."voip/<client>".path;
            '';
          };
          did = lib.mkOption {
            type = lib.types.nullOr lib.types.str;
            default = null;
            description = "Public number / DID in E.164 without '+' (e.g. 00493012345). Null = not assigned yet.";
          };
          displayName = lib.mkOption {
            type = lib.types.str;
            default = "";
            description = "Caller-ID display name (optional).";
          };
          enable = lib.mkOption {
            type = lib.types.bool;
            default = true;
            description = "Set false to keep a defined client dormant.";
          };
        };
      });
      default = {};
      description = ''
        SIP accounts keyed by client name (e.g. easybell-main, testnummer).
        Example:
          clients.easybell-main = {
            provider = "easybell";
            username = "K12345678";
            passwordFile = config.sops.secrets."voip/easybell-main".path;
            did = "00493012345";
          };
      '';
    };

    localTest = {
      enable = lib.mkEnableOption "provider-free local test extension (SIP client -> Asterisk -> playback)";

      extension = lib.mkOption {
        type = lib.types.str;
        default = "999";
        description = "Local extension number for the self-test (must not collide with services.asteriskLocal phone extensions).";
      };

      callerId = lib.mkOption {
        type = lib.types.str;
        default = "VoIP Test";
        description = "Caller-ID label for the test extension (documentation only in Phase 1).";
      };
    };
  };

  config = lib.mkMerge ([
    # Provider presets. Registrar values are per-product on Easybell's side:
    # SIP Trunk/VoIP -> voip.easybell.de, Cloud PBX -> pbx.easybell.de,
    # legacy single numbers -> sip.easybell.de:5060.
    # Sources (checked Sep 2026):
    # - easybell.de/help "General Instructions for VoIP Configuration"
    # - easybell.de/help "VoIP configuration for advanced users"
    # - easybell.de/hilfe "Asterisk Telefonanlagen" (official Asterisk-22 PJSIP guide)
    {
      services.voip.providers = {
        easybell = {
          registrar = lib.mkDefault "voip.easybell.de";
          port = lib.mkDefault 5060;
          transport = lib.mkDefault "udp";
          note = lib.mkDefault "SIP-Trunk/VoIP product. Cloud PBX uses pbx.easybell.de instead; legacy single numbers use sip.easybell.de:5060. Codec order per Easybell: G.722, G.711A, G.711U.";
        };
        # TODO: fill in once an Eventphone account exists. Stub proves the
        # provider abstraction is generic (not Easybell-only).
        eventphone = {
          registrar = null;
          note = "TODO: Eventphone registrar + product details.";
        };
      };
    }

    (lib.mkIf cfg.enable {
      assertions = [
        {
          assertion = !cfg.localTest.enable || hasAsterisk;
          message = "services.voip.localTest needs modules/nixos/asterisk.nix in the host imports (provides services.asteriskLocal).";
        }
      ]
      ++ lib.optional hasAsterisk {
        assertion = cfg.localTest.enable -> config.services.asteriskLocal.enable;
        message = "services.voip.localTest needs services.asteriskLocal.enable = true (the test extension runs on the local Asterisk).";
      }
      ++ [
        {
          assertion = lib.all (c: builtins.hasAttr c.provider cfg.providers) (builtins.attrValues enabledClients);
          message = "services.voip: a client references an unknown provider. Add it under services.voip.providers first.";
        }
        {
          assertion = lib.all (c: c.username != null && c.username != "") (builtins.attrValues enabledClients);
          message = "services.voip: every enabled client needs a username (no placeholder credentials; Easybell Fail2Ban-bans failing REGISTERs).";
        }
        {
          assertion = lib.all (c: c.passwordFile != "" && lib.hasPrefix "/" c.passwordFile) (builtins.attrValues enabledClients);
          message = "services.voip: every enabled client needs passwordFile as an absolute runtime path (e.g. config.sops.secrets.\"voip/<client>\".path).";
        }
        {
          assertion = lib.all (c: cfg.providers.${c.provider}.registrar != null) (builtins.attrValues enabledClients);
          message = "services.voip: a client uses a provider with registrar = null (TODO stub, e.g. eventphone). Fill in the registrar first.";
        }
        {
          assertion = let
            dids = lib.filter (d: d != null) (lib.mapAttrsToList (_n: c: c.did) enabledClients);
          in
            lib.length dids == lib.length (lib.unique dids);
          message = "services.voip: duplicate did values across enabled clients.";
        }
      ];

      warnings =
        lib.mapAttrsToList
        (_name: c: "services.voip: client passwordFile '${c.passwordFile}' points into the Nix store — the secret would be world-readable. Use /run/secrets/... via sops-nix instead.")
        (lib.filterAttrs (_name: c: lib.hasPrefix "/nix/store" c.passwordFile) enabledClients);

      # Phase-1 descriptors: public account data for admins + Phase-2 input.
      environment.etc = lib.mapAttrs' (name: client:
        lib.nameValuePair "voip/clients/${name}.conf" {
          text = clientDescriptor name client;
        })
      enabledClients;

      systemd.services.voip-check = {
        description = "Validate VoIP client credential files (Phase 1, no telephony yet)";
        wantedBy = ["multi-user.target"];
        after = ["network-online.target"];
        before = ["asterisk.service"];
        serviceConfig.Type = "oneshot";
        script = ''
          set -eu
          fail=0
          ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: c: ''
              if [ -r "${c.passwordFile}" ]; then
                echo "voip-check: client '${name}' credential file OK (${c.passwordFile})"
              else
                echo "voip-check: client '${name}' credential file MISSING/UNREADABLE: ${c.passwordFile}" >&2
                echo "voip-check: provide it via sops-nix (sops.secrets.\"voip/${name}\") — see docs/secrets.md" >&2
                fail=1
              fi
            '')
            enabledClients)}
          ${lib.optionalString cfg.localTest.enable ''
            echo "voip-check: local test extension ${cfg.localTest.extension} expected on Asterisk (dial ${cfg.localTest.extension} from any internal phone)"
          ''}
          exit $fail
        '';
      };
    })
  ]
  # Test extension via asteriskLocal's documented extension point
  # (types.lines concatenates with host config). List element absent
  # entirely without asterisk.nix (see hasAsterisk note above).
  ++ lib.optional hasAsterisk (lib.mkIf (cfg.enable && cfg.localTest.enable) {
    services.asteriskLocal.extraExtensions = localTestLines;
  }));
}
